### ISSUE TITLE
tempomat has not been registered 

### ISSUE THREAD

**Issue by kaiyes** [ospfranco/rn-macos-menubar-template#1]
![Screenshot 2020-05-24 at 4 01 51 PM](https://user-images.githubusercontent.com/5293742/82751332-3a9bb080-9dd8-11ea-8fd4-595c7069e02b.png)
However tray pops up without any view
![Screenshot 2020-05-24 at 4 05 27 PM](https://user-images.githubusercontent.com/5293742/82751356-67e85e80-9dd8-11ea-87ab-743a12a4c9db.png)

**Comment by ospfranco** [comment]
ah, sorry, forgot to change the module name on the app delegate, it needs to have the same name as the package in this case ospRnMenubarTemplate, give me one second I'll change it

**Comment by ospfranco** [comment]
done, you can pull again

**Comment by kaiyes** [comment]
Changed it myself. But thanks. It will now work for everyone. Thanks a lot. Tweet is underway !
![Screenshot 2020-05-24 at 4 13 40 PM](https://user-images.githubusercontent.com/5293742/82751522-9fa3d600-9dd9-11ea-89cc-4e6425ac95b1.png)

**Comment by ospfranco** [comment]
Cheers

**Comment by kaiyes** [comment]
I had one other question though. Is this normal ? Having an icon popping up in doc ? 
![Screenshot 2020-05-24 at 4 22 16 PM](https://user-images.githubusercontent.com/5293742/82751922-72a4f280-9ddc-11ea-9137-9d0ced111039.png)

**Comment by ospfranco** [comment]
yeah, has to do with the UI agent flag, if you turn it on then the app will really only live inside the menu bar and nowhere else
