### ISSUE TITLE
[Questions] Why Embed swift is no + no Application is agent ? 

### ISSUE THREAD

**Issue by kaiyes** [ospfranco/rn-macos-menubar-template#2]
Hi,
I have a few questions please. Just out of curiosity, I dug into xcode. I was surprised to see that Embed Swift is no everywhere and there is no sign of Application is agent as mentioned in the blog post. 

I was wondering why is that ? 

![Screenshot 2020-05-24 at 5 12 31 PM](https://user-images.githubusercontent.com/5293742/82752730-ea295080-9de1-11ea-813e-e791e339f700.png)
![Screenshot 2020-05-24 at 5 11 32 PM](https://user-images.githubusercontent.com/5293742/82752732-edbcd780-9de1-11ea-880b-850cc16ec043.png)
![Screenshot 2020-05-24 at 5 11 27 PM](https://user-images.githubusercontent.com/5293742/82752734-f3b2b880-9de1-11ea-9e7d-15308100ef55.png)

**Comment by ospfranco** [comment]
true, I will update the article, it is a bid hard to explain, but it all has to do with Flipper, as far as I could figure out, if you don't turn off dead code stripping then compilation will fail with a swift error, turning on always embed swift libraries was just one step I took to get compilation to work.

Application is agent is not 100% necessary, it might be useful to have it disabled when first developing your app to be able to alt-tab into it, since the UI agent can easily loose focus

**Comment by kaiyes** [comment]
Ah, ok. Your open source repo works beautifully. But just to understand how it works, I am still trying to init a fresh react native project, then init macos and try to get a fresh menu bar application going from scratch. At the moment, I don't get any errors app builds yet I don't see any app in the menu bar.

**Comment by ospfranco** [comment]
the contents of the AppDelegate.swift is what you are looking for, there I initialize a statusbar button and set the react rootView to control it

**Comment by kaiyes** [comment]
Yeah I copied your AppDelegate.swift, changed the moduleName too. Experimented with turning agent on/off and embedding swift library on/off. Nothing happens. 
https://github.com/kaiyes/Deepr
Just don't know what's going wrong. How come it builds but doesn't show anything ?

**Comment by ospfranco** [comment]
![Screenshot 2020-05-24 at 16 20 02](https://user-images.githubusercontent.com/1634213/82756424-864f5980-9dda-11ea-88f4-f6fd97e8e8cb.JPG)

As stated, you need to select your module on the main.storyboard file

**Comment by kaiyes** [comment]
Hey Thanks a ton ! Awesome ! it works now !
